/*
Chao Lin
Robert Leese
CS 286
Dr.Dale
American Civil War
*/

var first = {
	'battleOfFortSumter' : {'name':"Battle of Fort Sumter",
						 	'date':'1861-04-12',
 						  	'totalCasualty': 0,
 						  	'unionCasualty': 0,
 						  	'confedCasualty': 0,
 						  	'victor':'confederate',
 						  	'lat':32.82,
 						  	'lon':-79.90,
							'description':"The battle of Fort Sumter was what started it all. This two day bombardment of the fort was a result of the U.S. military refusing to leave the fort in the Charleston Bay after South Carolina demanded they abandon the Fort, which they considered to be in Confederate territory. This became the first crisis President Lincoln would have to deal with, having been inaugurated barely a month before. The seige ended with no casulaties when Major Robert Anderson agreed to evacuate, after 34 hours of continuous artillery fire"},

   	'firstBattleOfBullRun' : {'name':"First Battle of Bull Run",
						  	  'date':'1861-07-21',
 						  	  'totalCasualty': 4690,
 						  	  'unionCasualty': 2708,
 						  	  'confedCasualty': 1982,
 						  	  'victor':'confederate',
 						  	  'lat':38.81,
 						  	  'lon':-77.52,
							  'description':"Also known as the Battle of First Manasses, this was the first major engagement of the war. Expecting a quick end to the war, Brig. Gen. Irving McDowell led his inexperienced army towards Richmond to take the Confederate Capitol. They came across a large Confederate army at the Occoquan River, and his poorly trained men failed a surprise flank, and the battle raged on until Confederate reinforcements were able to arrive by railcar. The Union troops were forced to retreat, as General Stonewall Jackson launched a strong counter attack."}
};

/*--------------------------------------------------------------*/

var second = {
	'battleOfFortDonelson' : {'name':"Battle of Fort Donelson",
						  	  'date':'1862-02-11',
 						  	  'totalCasualty': 16537,
 						  	  'unionCasualty': 2691,
 						  	  'confedCasualty': 13846,
 						  	  'victor':'union',
 						  	  'lat':36.49,
 						  	  'lon':-87.86,
							  'description':"General Ulysses Grant first tried to capture this fort through the use of gunboats, but that strategy failed under return fire from the fort. The next day, Grant had Fort Donelson surrounded, and Confederate general John Floyd launched a surprise attack to try and open up an escape route. The attack failed, which lead to unconditional surrender"},

	'battleOfShiloh' : {'name':"Battle of Shiloh",
						'date':'1862-04-06',
 						'totalCasualty': 23746,
 						'unionCasualty': 13047,
 						'confedCasualty': 10699,
 						'victor':'union',
 						'lat':35.15,
 						'lon':-88.32,
						'description':"A Union army under Major General Ulysses S. Grant had moved via the Tennessee River deep into Tennessee and was encamped principally at Pittsburg Landing, Tennessee on the west bank of the river, where Confederate forces under Generals Albert Sidney Johnston and Pierre G. T. Beauregard launched a surprise attack on Grant's army. Johnston was killed in action during the fighting; Beauregard, who thus succeeded to command of the army, decided against pressing the attack late in the evening. Overnight Grant received considerable reinforcements from another Union army under Maj. Gen. Don Carlos Buell, allowing him to launch an unexpected counterattack the next morning which completely reversed the Confederate gains of the previous day."}
};
/*---------------------------------------------------------------*/
var third = {
	'battleOfSevenPines' : {'name':"Battle of Seven Pines",
						    'date':'1862-05-31',
 						    'totalCasualty': 11165,
 						    'unionCasualty': 5031,
 						    'confedCasualty': 6134,
 						    'victor':'inconclusive',
 						    'lat':37.52,
 						    'lon':-77.30,
							'description':"This battle began when Confederate general Joseph Johnston tried to launch a surprise attack on two Federal Corps that appeared to be cut off from Union aide. As Union reinforcements did indeed arrive, both sides fed more men into the battle. Both sides faced heavy casualties, however neither gained any tactical advantage as a result."},

	'battleOfGainesMill' : {'name':"Battle of Gaines' Mill",
						    'date':'1862-06-27',
 						    'totalCasualty': 14830,
 						    'unionCasualty': 6837,
 						    'confedCasualty': 7993,
 						    'victor':'confederate',
 						    'lat':37.59,
 						    'lon':-77.29,
							'description':"Also known as the First Battle of Cold Harbor, or the Battle of the Chickahominy River, this battle came one day after the Battle of Beaver Dam Creek. General Robert E. Lee lead a Confederate offensive against the rightmost flank of the Army of the Potomac in what would be the largest Confederate attack of the war. The Union soldiers held of the uncoordinate attack for most of an afternoon, but once dusk fell, General Stonewall Jackson was able to lead a successful advance, pushing the Union back across the river. This saved Richmond, and forced Brig. Gen. George McClellan to abandon his campaign for the Confederate Capitol."},

	'battleOfMalvernHill' : {'name':"Battle of Malvern Hill",
						    'date':'1862-07-01',
 						    'totalCasualty': 8650,
 						    'unionCasualty': 3000,
 						    'confedCasualty': 5650,
 						    'victor':'union',
 						    'lat':37.41,
 						    'lon':-77.25,
							'description':"The Battle of Malvern Hill, also known as the Battle of Poindexter's Farm, was the final battle of the Seven Days Battles. The Seven Days Battles were the climax of the Peninsula Campaign, during which McClellan's Army of the Potomac sailed around the Confederate lines, landed at the tip of the Virginia Peninsula, southeast of Richmond, and struck inland towards the Confederate capital. Confederate commander-in-chief Joseph E. Johnston fended off McClellan's repeated attempts to take the city, slowing Union progress on the peninsula to a crawl. When Johnston was wounded, Lee took command and launched a series of counterattacks, collectively called the Seven Days Battles. These attacks culminated in the action on Malvern Hill."},			

	'battleOfCedarMountain' : {'name':"Battle of Cedar Mountain",
						  	   'date':'1862-08-09',
 						  	   'totalCasualty': 3691,
 						  	   'unionCasualty': 2353,
 						  	   'confedCasualty': 1338,
 						  	   'victor':'confederate',
 						  	   'lat':38.40,
 						  	   'lon':-78.07,
							   'description':"The Battle of Cedar Mountain, also known as Slaughter's Mountain or Cedar Run, consited of Union forces under Maj. Gen. Nathaniel P. Banks attacked Confederate forces under Maj. Gen. Stonewall Jackson near Cedar Mountain as the Confederates marched on Culpeper Court House to forestall a Union advance into central Virginia. After nearly being driven from the field in the early part of the battle, a Confederate counterattack broke the Union lines resulting in a Confederate victory. The battle was the first combat of the Northern Virginia Campaign."},	  

	'secondBattleOfBullRun' : {'name':"Second Battle Of Bull Run",
						  	   'date':'1862-08-28',
 						  	   'totalCasualty':20300,
 						  	   'unionCasualty': 12000,
 						  	   'confedCasualty': 8300,
 						  	   'victor':'confederate',
 						  	   'lat':38.81,
 						  	   'lon':-77.52,
							   'description':"Also known as the Battle of Second Manassas.  It was the culmination of an offensive campaign waged by Confederate Gen. Robert E. Lee's Army of Northern Virginia against Union Maj. Gen. John Pope's Army of Virginia, and a battle of much larger scale and numbers than the First Battle of Bull Run (or First Manassas) fought on July 21, 1861 on the same ground. Confederate Maj. Gen. Stonewall Jackson captured the Union supply depot at Manassas Junction, threatening Pope's line of communications with Washington, D.C. Jackson attacked a Union column just east of Gainesville, at Brawner's Farm, resulting in a stalemate. On that same day, the wing of Lee's army commanded by Maj. Gen. James Longstreet broke through light Union resistance in the Battle of Thoroughfare Gap and approached the battlefield. When massed Confederate artillery devastated a Union assault by Maj. Gen. Fitz John Porter's V Corps, Longstreet's wing of 25,000 men in five divisions counterattacked in the largest simultaneous mass assault of the war.[10] The Union left flank was crushed and the army was driven back to Bull Run. "},

	'battleOfSouthMountain' : {'name':"Battle of South Mountain",
 						  	   'date':'1862-09-14',
 						  	   'totalCasualty': 5010,
 						  	   'unionCasualty': 2325,
 						  	   'confedCasualty': 2685,
 						  	   'victor':'union',
 						  	   'lat':39.48,
 						  	   'lon':-77.62,
							   'description':"The Battle of South Mountain—known in several early Southern accounts as the Battle of Boonsboro Gap—consisted of three pitched battles were fought for possession of three South Mountain passes: Crampton's, Turner's, and Fox's Gaps. Maj. Gen. George B. McClellan, commanding the Union Army of the Potomac, needed to pass through these gaps in his pursuit of Confederate General Robert E. Lee's precariously divided Army of Northern Virginia. Although the delay bought at South Mountain would allow him to reunite his army and forestall defeat in detail, Lee considered termination of the Maryland Campaign at nightfall."},	 	 

	'battleOfAntietam' : {'name':"Battle of Antietam",
 						  'date':'1862-09-17',
 						  'totalCasualty': 25410,
 						  'unionCasualty': 12410,
 						  'confedCasualty': 13000,
 						  'victor':'inconclusive',
 						  'lat':39.47,
 						  'lon':-77.74,
						  'description':"Also known as the Battle of Sharpsburg, particularly in the South, was the first major battle in the American Civil War to take place on Union soil. It is the bloodiest single-day battle in American history, with a combined tally of 25,410 dead, wounded, or missing. After pursuing Confederate General Robert E. Lee into Maryland, Union Army Maj. Gen. George B. McClellan launched attacks against Lee's army, in defensive positions behind Antietam Creek. Although outnumbered two-to-one, Lee committed his entire force, while McClellan sent in less than three-quarters of his army, enabling Lee to fight the Federals to a standstill. During the night, both armies consolidated their lines. In spite of crippling casualties, Lee continued to skirmish with McClellan throughout September 18, while removing his battered army south of the Potomac River. McClellan had halted Lee's invasion of Maryland, but Lee was able to withdraw his army back to Virginia without interference from the cautious McClellan. Although the battle was tactically inconclusive, the Confederate troops had withdrawn first from the battlefield, making it, in military terms, a Union victory."},	

	'battleOfPerryvile' : {'name':"Battle of Perryvile",
 						   'date':'1862-10-08',
 						   'totalCasualty': 7637,
 						   'unionCasualty': 4241,
 						   'confedCasualty': 3396,
 						   'victor':'union',
 						   'lat':37.68,
 						   'lon':-84.97,
						   'description':"Also known as the Battle of Chaplin Hills, was the culmination of the Confederate Heartland Offensive (Kentucky Campaign). Confederate Gen. Braxton Bragg's Army of Mississippi[10] won a tactical victory against primarily a single corps of Maj. Gen. Don Carlos Buell's Union Army of the Ohio. The battle is considered a strategic Union victory, sometimes called the Battle for Kentucky, since Bragg withdrew to Tennessee soon thereafter. The Union retained control of the critical border state of Kentucky for the remainder of the war."}	
};
/*------------------------------------------------------------------*/
var fourth = {
	'battleOfFredericksburg' : {'name':"Battle of Fredericksburg",
 						  		'date':'1862-12-11',
 						  		'totalCasualty': 18030,
 						  		'unionCasualty': 12653,
 						  		'confedCasualty': 5377,
 						 		'victor':'confederate',
 						  		'lat':38.30,
 						 		'lon':-77.47,
								'description':"The Union Army's futile frontal attacks on December 13 against entrenched Confederate defenders on the heights behind the city is remembered as one of the most one-sided battles of the American Civil War, with Union casualties more than twice as heavy as those suffered by the Confederates. Burnside's plan was to cross the Rappahannock River at Fredericksburg in mid-November and race to the Confederate capital of Richmond before Lee's army could stop him.  the Grand Division of Maj. Gen. William B. Franklin was able to pierce the first defensive line of Confederate Lieutenant General Stonewall Jackson to the south, but was finally repulsed. Burnside ordered the grand divisions of Maj. Gens. Edwin V. Sumner and Joseph Hooker to make multiple frontal assaults against Lt. Gen. James Longstreet's position on Marye's Heights, all of which were repulsed with heavy losses."},	

	'battleOfStonesRiver' : {'name':"Battle of Stones River",
 						  	 'date':'1862-12-31',
 						  	 'totalCasualty': 24645,
 						  	 'unionCasualty': 12906,
 						  	 'confedCasualty': 11739,
 						  	 'victor':'union',
 						  	 'lat':35.88,
 						  	 'lon':-86.44,
							 'description':"The Battle of Stones River or Second Battle of Murfreesboro, was the culmination of the Stones River Campaign in the Western Theater.  Of the major battles of the Civil War, Stones River had the highest percentage of casualties on both sides. Although the battle itself was inconclusive, the Union Army's repulse of two Confederate attacks and the subsequent Confederate withdrawal were a much-needed boost to Union morale after the defeat at the Battle of Fredericksburg, and it dashed Confederate aspirations for control of Middle Tennessee. "}

};
/*-------------------------------------------------------------------*/
var fifth = {
	'siegeOfVicksburg' : {'name':"Siege of Vicksburg",
 						  'date':'1863-05-18',
 						  'totalCasualty': 37532,
 						  'unionCasualty': 4835,
 						  'confedCasualty': 32697,
 						  'victor':'union',
 						  'lat':32.34,
 						  'lon':-90.85,
						  'description':"The Siege of Vicksburg was the final major military action in the Vicksburg Campaign. In a series of maneuvers, Union Maj. Gen. Ulysses S. Grant and his Army of the Tennessee crossed the Mississippi River and drove the Confederate Army of Mississippi led by Lt. Gen. John C. Pemberton into the defensive lines surrounding the fortress city of Vicksburg, Mississippi. Vicksburg was the last major Confederate stronghold on the Mississippi River; therefore, capturing it completed the second part of the Northern strategy, the Anaconda Plan. When two major assaults (May 19 and 22, 1863) against the Confederate fortifications were repulsed with heavy casualties, Grant decided to besiege the city beginning on May 25. With no reinforcement, supplies nearly gone, and after holding out for more than forty days, the garrison finally surrendered on July 4."},	

	'siegeOfPortHudson' : {'name':"Battle of Port Hudson",
 						  	'date':'1863-05-21',
 						  	'totalCasualty': 17500,
 						  	'unionCasualty': 10000,
 						  	'confedCasualty': 7500,
 						  	'victor':'union',
 						  	'lat':30.69,
 						  	'lon':-91.28,
							'description':"While Union General Ulysses Grant was besieging Vicksburg upriver, General Nathaniel Banks was ordered to capture the Confederate stronghold of Port Hudson, in order to go to Grant's aid. When his assault failed, Banks settled into a 48-day siege, the longest in US military history. A second attack also failed, and it was only after the fall of Vicksburg that the Confederate commander, General Franklin Gardner surrendered the port. This left the Mississippi open to Union navigation from its source to the Gulf of Mexico."},		

	'battleOfGettysburg' : {'name':"Battle of Gettysburg",
 						    'date':'1863-07-01',
 						    'totalCasualty': 51049,
 						    'unionCasualty': 23049,
 						    'confedCasualty': 28000,
 						    'victor':'union',
 						    'lat':39.81,
 						    'lon':-77.23,
							'description':" This battle involved the largest number of casualties of the entire war and is often described as the war's turning point. After his success at Chancellorsville in Virginia in May 1863, Lee led his army through the Shenandoah Valley to begin his second invasion of the North—the Gettysburg Campaign. With his army in high spirits, Lee intended to shift the focus of the summer campaign from war-ravaged northern Virginia and hoped to influence Northern politicians to give up their prosecution of the war by penetrating as far as Harrisburg, Pennsylvania, or even Philadelphia. Elements of the two armies initially collided at Gettysburg on July 1, 1863, as Lee urgently concentrated his forces there, his objective being to engage the Union army and destroy it. Lee launched a heavy assault on the Union left flank, and fierce fighting raged at Little Round Top, the Wheatfield, Devil's Den, and the Peach Orchard. On the Union right, Confederate demonstrations escalated into full-scale assaults on Culp's Hill and Cemetery Hill. All across the battlefield, despite significant losses, the Union defenders held their lines. On the third day of battle, fighting resumed on Culp's Hill, and cavalry battles raged to the east and south, but the main event was a dramatic infantry assault by 12,500 Confederates against the center of the Union line on Cemetery Ridge, known as Pickett's Charge. The charge was repulsed by Union rifle and artillery fire, at great loss to the Confederate army. Lee led his army on a torturous retreat back to Virginia. Between 46,000 and 51,000 soldiers from both armies were casualties in the three-day battle."},

	'battleOfChickamauga' : {'name':"Battle of Chickamauga",
 						  	 'date':'1863-09-19',
 						  	 'totalCasualty': 34624,
 						  	 'unionCasualty': 16170,
 						  	 'confedCasualty': 18454,
 						  	 'victor':'confederate',
 						  	 'lat':34.92,
 						  	 'lon':-85.26,
							 'description':"This Battle marked the end of a Union offensive in southeastern Tennessee and northwestern Georgia called the Chickamauga Campaign. The battle was the most significant Union defeat in the Western Theater of the American Civil War and involved the second highest number of casualties in the war following the Battle of Gettysburg. It was the first major battle of the war that was fought in Georgia."}
};
/*---------------------------------------------------------------*/
var sixth = {
	'battleOfChattanooga' : {'name':"Battle of Chattanooga",
 						  	 'date':'1863-11-23',
 						  	 'totalCasualty': 13824,
 						  	 'unionCasualty': 5824,
 						  	 'confedCasualty': 8000,
 						  	 'victor':'union',
 						  	 'lat':35.05,
 						  	 'lon':-85.31,
							 'description':"This was the final battle in the Chattanooga Campaign, which was a 2 month long series of battles throughout the Chattanooga area. The Union forces under the command of Ulysses S. Grant were able to push the Confederate Army of Tennessee off of the high ground."}		
};
 /*---------------------------------------------------------------*/	
var seventh = {
	'battleOfWilderness' : {'name':"Battle of the Wilderness",
 						  	'date':'1864-05-05',
 						  	'totalCasualty': 28699,
 						  	'unionCasualty': 17666,
 						  	'confedCasualty': 11033,
 						  	'victor':'inconclusive',
 						  	'lat':38.32,
 						  	'lon':-77.76,
							'description':"The Battle of the Wilderness was the first battle of Lt. Gen. Ulysses S. Grant's 1864 Virginia Overland Campaign against Gen. Robert E. Lee and the Confederate Army of Northern Virginia. Both armies suffered heavy casualties, a harbinger of a bloody war of attrition by Grant against Lee's army and, eventually, the Confederate capital, Richmond, Virginia. The battle was tactically inconclusive, as Grant disengaged and continued his offensive."},

	'battleOfSpotsylvania' : {'name':"Battle of Spotsylvania",
 						  	  'date':'1864-05-08',
 						  	  'totalCasualty': 31086,
 						  	  'unionCasualty': 18399,
 						  	  'confedCasualty': 12687,
 						  	  'victor':'inconclusive',
 						  	  'lat':38.22,
 						  	  'lon':-77.60,
							  'description':"The Battle of Spotsylvania Court House, sometimes more simply referred to as the Battle of Spotsylvania (or the 19th-century spelling Spottsylvania), was the second major battle in Lt. Gen. Ulysses S. Grant's 1864 Overland Campaign. Following the bloody but inconclusive Battle of the Wilderness, Grant's army disengaged from Confederate General Robert E. Lee's army and moved to the southeast, attempting to lure Lee into battle under more favorable conditions. Elements of Lee's army beat the Union army to the critical crossroads of Spotsylvania Court House, Virginia and began entrenching. In the end, the battle was tactically inconclusive, but with almost 32,000 casualties on both sides, it was the costliest battle of the campaign."},

	'battleOfResaca' : {'name':"Battle of Resaca",
 						'date':'1864-05-13',
 						'totalCasualty': 7800,
 						'unionCasualty': 5000,
 						'confedCasualty': 2800,
 						'victor':'inconclusive',
 						'lat':34.58,
 						'lon':-84.94,
						'description':"This battle was waged in both Gordon and Whitfield counties, Georgia. It ended inconclusively with the Confederate Army retreating. The engagement was fought between the Military Division of the Mississippi (led by Maj. Gen. William T. Sherman) on the side of the Union and the Army of Tennessee (Gen. Joseph E. Johnston) for the Confederates."},

	'battleOfColdHarbor' : {'name':"Battle of Cold Harbor",
 						    'date':'1864-05-31',
 						    'totalCasualty': 18025,
 						    'unionCasualty': 12738,
 						    'confedCasualty': 5287,
 						    'victor':'confederate',
 						    'lat':37.59,
 						    'lon':-77.29,
							'description':"The Battle of Cold Harbor was one of the final battles of Union Lt. Gen. Ulysses S. Grant's Overland Campaign during the American Civil War, and is remembered as one of American history's bloodiest, most lopsided battles. Thousands of Union soldiers were killed or wounded in a hopeless frontal assault against the fortified positions of Confederate Gen. Robert E. Lee's army."},

	'battleOfAtlanta' : {'name':"Battle of Atlanta",
 						 'date':'1864-07-22',
 						 'totalCasualty': 9141,
 						 'unionCasualty': 3641,
 						 'confedCasualty': 5500,
 						 'victor':'union',
 						 'lat':33.75,
 						 'lon':-84.35,
						 'description':"Continuing their summer campaign to seize the important rail and supply center of Atlanta, Union forces commanded by William T. Sherman overwhelmed and defeated Confederate forces defending the city under John B. Hood. Union Maj. Gen. James B. McPherson was killed during the battle. The fall of Atlanta was especially noteworthy for its political ramifications. In the 1864 election, former Union general George B. McClellan, a Democrat, ran against President Lincoln, on a peace platform calling for a truce with the Confederacy. The capture of Atlanta and Hood's burning of military facilities as he evacuated, were extensively covered by Northern newspapers, significantly boosting Northern morale, and Lincoln was reelected by a large margin."},	

	'battleOfCrater' : {'name':"Battle of the Crater",
 						'date':'1864-07-30',
 						'totalCasualty': 5289,
 						'unionCasualty': 3798,
 						'confedCasualty': 1491,
 						'victor':'confederate',
 						'lat':37.21,
 						'lon':-77.37,
						'description':"After weeks of preparation, on July 30, Union forces exploded a mine in Maj. Gen. Ambrose E. Burnside's IX Corps sector, blowing a gap in the Confederate defenses of Petersburg, Virginia. From this propitious beginning, everything deteriorated rapidly for the Union attackers. Unit after unit charged into and around the crater, where soldiers milled in confusion. Grant considered the assault \"the saddest affair I have witnessed in the war.\" The Confederates quickly recovered and launched several counterattacks led by Brig. Gen. William Mahone. The breach was sealed off, and Union forces were repulsed with severe casualties. Burnside was relieved of command for the last time for his role in the debacle, and he was never again returned to command."},	

	'battleOfGlobeTavern' : {'name':"Battle of Globe Tavern",
 						     'date':'1864-08-18',
 						  	 'totalCasualty': 5916,
 						  	 'unionCasualty': 4296,
 						  	 'confedCasualty': 1620,
 						  	 'victor':'union',
 						  	 'lat':37.17,
 						  	 'lon':-77.42,
							 'description':"The Battle of Globe Tavern, also known as the Second Battle of the Weldon Railroad, was the second attempt of the Union Army to sever the Weldon Railroad during the Siege of Petersburg of the American Civil War. A Union force under Maj. Gen. Gouverneur K. Warren destroyed miles of track and withstood strong attacks from Confederate troops under Gen. P.G.T. Beauregard and Lt. Gen. A.P. Hill. It was the first Union victory in the Richmond-Petersburg Campaign. It forced the Confederates to carry their supplies 30 miles (48 km) by wagon to bypass the new Union lines that were extended farther to the south and west."},

	'battleOfJonesborough' : {'name':"Battle of Jonesborough",
 						  	  'date':'1864-08-31',
 						  	  'totalCasualty': 3849,
 						  	  'unionCasualty': 1149,
 						  	  'confedCasualty': 2700,
 						  	  'victor':'union',
 						  	  'lat':33.53,
 						  	  'lon':-84.36,
							  'description':"Two Union armies led by Maj. Gen. William T. Sherman maneuvered to draw the Army of Tennessee (led by John Bell Hood) away from their defenses at Atlanta, Georgia, where it could be destroyed. Although Hood's army was not destroyed, the city of Atlanta was abandoned and then occupied by Union troops for the rest of the war. The fall of Atlanta also had far-reaching political as well as military effects on the course of the war."}	
};
/*-------------------------------------------------------------*/
var eighth = {
	'battleOfCedarCreek' : {'name':"Battle of Cedar Creek",
 						  	'date':'1864-10-19',
 						  	'totalCasualty': 8575,
 						  	'unionCasualty': 5665,
 						  	'confedCasualty': 2910,
 						  	'victor':'union',
 						  	'lat':39.02,
 						  	'lon':-78.30,
							'description':"The Battle of Cedar Creek, or Battle of Belle Grove, was the culminating battle of the Valley Campaigns of 1864. Confederate Lt. Gen. Jubal Early launched a surprise attack against the encamped army of Union Maj. Gen. Philip Sheridan, across Cedar Creek, northeast of Strasburg, Virginia. During the morning fighting, seven Union infantry divisions were forced to fall back and lost numerous prisoners and cannons. Early failed to continue his attack north of Middletown, and Sheridan, dramatically riding to the battlefield from Winchester, was able to rally his troops to hold a new defensive line. A Union counterattack that afternoon routed Early's army."},	

	'battleOfFranklin' : {'name':"Battle of Franklin",
 						  'date':'1864-11-29',
 						  'totalCasualty': 8578,
 						  'unionCasualty': 2326,
 						  'confedCasualty': 6252,
 						  'victor':'union',
 						  'lat':35.91,
 						  'lon':-86.87,
						  'description':"This was one of the worst disasters of the war for the Confederate States Army. Confederate Lt. Gen. John Bell Hood's Army of Tennessee conducted numerous frontal assaults against fortified positions occupied by the Union forces under Maj. Gen. John M. Schofield and was unable to break through or to prevent Schofield from a planned, orderly withdrawal to Nashville."},	

	'battleOfNashville' : {'name':"Battle of Nashville",
 						   'date':'1864-11-30',
 						   'totalCasualty': 9061,
 						   'unionCasualty': 3061,
 						   'confedCasualty': 6000,
 						   'victor':'union',
 						   'lat':36.08,
 						   'lon':-86.80,
						   'description':"The Battle of Nashville was a two-day battle in the Franklin-Nashville Campaign that represented the end of large-scale fighting west of Georgia, South Carolina, North Carolina, and Virginia. In one of the largest victories achieved by the Union Army during the war, Thomas attacked and routed Hood's army, largely destroying it as an effective fighting force."},	

	'battleOfBentonville' : {'name':"Battle of Bentonville",
 						  	'date':'1865-03-10',
 						  	'totalCasualty': 4133,
 						  	'unionCasualty': 1527,
 						  	'confedCasualty': 2606,
 						  	'victor':'union',
 						  	'lat':35.25,
 						  	'lon':-78.67,
							'description':"As the right wing of Sherman's army under command of Maj. Gen. Oliver O. Howard marched toward Goldsborough, the left wing under command of Maj. Gen. H. W. Slocum encountered the entrenched men of Johnston's army.The Confederates were able to repulse the attack as Sherman ordered Mower back to connect with his own corps. Johnston elected to withdraw from the battlefield that night. As a result of the overwhelming Union strength and the heavy casualties his army suffered in the battle, Johnston surrendered to Sherman little more than a month later at Bennett Place, near Durham Station. Coupled with Gen. Robert E. Lee's surrender earlier in April, Johnston's surrender represented the effective end of the war."},		

	'battleOfFiveForks' : {'name':"Battle of Five Forks",
 						   'date':'1865-04-01',
 						   'totalCasualty': 3780,
 						   'unionCasualty': 830,
 						   'confedCasualty': 2950,
 						   'victor':'union',
 						   'lat':37.13,
 						   'lon':-77.62,
						   'description':"A mobile task force of combined infantry, artillery and cavalry from the Union Army commanded by Major General Philip Sheridan defeated a Confederate States Army combined task force from the Army of Northern Virginia commanded by Major General George E. Pickett. The Union force inflicted over 1,000 casualties on the Confederates and took between 2,400 and 4,000 prisoners while seizing Five Forks, the key to control of the South Side Railroad (sometimes shown as Southside Railroad), a vital Confederate supply line to, and retreat line from, Petersburg."},	

	'battleOfSailorsCreek' : {'name':"Battle of Sailor's Creek",
 						  	  'date':'185-04-06',
 						  	  'totalCasualty': 8848,
 						  	  'unionCasualty': 1148,
 						  	  'confedCasualty': 7700,
 						  	  'victor':'union',
 						  	  'lat':37.30,
 						  	  'lon':-78.22,
							  'description':"The Battle of Sailor's Creek (also known in whole or in part as Sayler's Creek, Little Sailor's Creek, Harper's Farm, Marshall's Cross Roads, Hillsman Farm, Double Bridges, or Lockett's Farm) was the last major engagement between the armies of Confederate General Robert E. Lee and Union Army General-in-chief Lieutenant General Ulysses S. Grant before the capitulation of Lee's Army of Northern Virginia at Appomattox Court House three days later."}
};	

